import type {
  ReportCatalogItemView,
  ReportCode,
  ReportSnapshotColumn,
} from "@tashkalinskaya/contracts";

export const REPORT_TEMPLATE_VERSION = "b18-v2";

export interface ReportDefinition extends ReportCatalogItemView {
  readonly columns: readonly ReportSnapshotColumn[];
}

const column = (
  key: string,
  label: string,
  width: number,
  numeric = false,
  total = false,
): ReportSnapshotColumn => ({ key, label, numeric, total, width });

export const REPORT_DEFINITIONS: Readonly<Record<ReportCode, ReportDefinition>> = {
  PRODUCTION_OUTBOUND: {
    code: "PRODUCTION_OUTBOUND",
    title: "Производство и вывоз",
    description: "Выпуск, чистый вывоз после принятого годного возврата и остаток обычного склада.",
    formats: ["XLSX"],
    personalData: false,
    columns: [
      column("productCode", "Код", 14),
      column("productName", "Наименование", 34),
      column("producedQuantity", "Произведено", 15, true, true),
      column("outboundQuantity", "Вывезено", 15, true, true),
      column("onHandQuantity", "На складе", 15, true, true),
    ],
  },
  MOVEMENTS: {
    code: "MOVEMENTS",
    title: "Движение готовой продукции",
    description: "Неизменяемый складской журнал по документам и корзинам.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("documentType", "Документ", 22),
      column("productCode", "Код", 14),
      column("productName", "Товар", 28),
      column("source", "Откуда", 22),
      column("target", "Куда", 22),
      column("quantity", "Количество", 13, true, true),
      column("actor", "Сотрудник", 24),
      column("createdAt", "Время", 20),
    ],
  },
  PLAN_FACT: {
    code: "PLAN_FACT",
    title: "План / факт производства",
    description: "Текущий опубликованный план, выпуск и принятая складом продукция.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("workshop", "Цех", 22),
      column("productCode", "Код", 14),
      column("productName", "Товар", 28),
      column("plan", "План", 12, true, true),
      column("produced", "Выпущено", 12, true, true),
      column("accepted", "Принято", 12, true, true),
      column("difference", "Отклонение", 13, true, true),
    ],
  },
  DEFECTS: {
    code: "DEFECTS",
    title: "Производственный брак",
    description: "Заявленный брак, причина и результат подтверждения.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("workshop", "Цех", 22),
      column("product", "Товар", 28),
      column("quantity", "Количество", 13, true, true),
      column("reason", "Причина", 24),
      column("status", "Статус", 20),
      column("reportedBy", "Сообщил", 22),
      column("comment", "Комментарий", 34),
    ],
  },
  RECEIPTS: {
    code: "RECEIPTS",
    title: "Приемка складом",
    description: "Переданные партии, принятые и отклоненные количества.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("workshop", "Цех", 22),
      column("product", "Товар", 28),
      column("declared", "Передано", 12, true, true),
      column("accepted", "Принято", 12, true, true),
      column("rejected", "Отклонено", 12, true, true),
      column("status", "Статус", 20),
      column("receivedBy", "Кладовщик", 22),
    ],
  },
  LOADINGS: {
    code: "LOADINGS",
    title: "Погрузка по территориям",
    description: "Строки погрузки и состояние двойного подтверждения.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("territory", "Территория", 18),
      column("driver", "Водитель", 22),
      column("product", "Товар", 28),
      column("quantity", "Количество", 13, true, true),
      column("lineStatus", "Строка", 18),
      column("sessionStatus", "Погрузка", 20),
      column("confirmation", "Подтверждение", 24),
    ],
  },
  RETURNS: {
    code: "RETURNS",
    title: "Годный возврат",
    description: "Прием возврата и его распределение между территориями.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("operation", "Операция", 20),
      column("source", "Источник / территория", 24),
      column("product", "Товар", 28),
      column("quantity", "Количество", 13, true, true),
      column("status", "Статус", 20),
      column("actor", "Сотрудник", 22),
    ],
  },
  SPOILAGE: {
    code: "SPOILAGE",
    title: "Порча и списания",
    description: "Физическая порча, решение и ручная сверка внешнего документа.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("source", "Источник", 20),
      column("product", "Товар", 28),
      column("quantity", "Количество", 13, true, true),
      column("reason", "Причина", 24),
      column("status", "Статус", 18),
      column("externalCheck", "Сверка 1С", 18),
      column("createdBy", "Создал", 22),
    ],
  },
  INVENTORY: {
    code: "INVENTORY",
    title: "Инвентаризация",
    description: "Системный и физический остаток с найденными расхождениями.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("version", "Версия", 10),
      column("productCode", "Код", 14),
      column("productName", "Товар", 28),
      column("system", "По системе", 13, true, true),
      column("actual", "По факту", 13, true, true),
      column("difference", "Расхождение", 13, true, true),
      column("status", "Статус", 18),
    ],
  },
  NORMS: {
    code: "NORMS",
    title: "Недельные нормы",
    description: "Действующие версии норм по территории, дню недели и товару.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("territory", "Территория", 18),
      column("weekday", "День недели", 16),
      column("productCode", "Код", 14),
      column("productName", "Товар", 28),
      column("quantity", "Норма", 12, true, true),
      column("validFrom", "Действует с", 12),
      column("validUntil", "Действует по", 13),
      column("source", "Источник", 18),
    ],
  },
  ATTENDANCE: {
    code: "ATTENDANCE",
    title: "Табель сотрудников",
    description: "Приход, уход, отработанное время и контрольные признаки.",
    formats: ["XLSX", "PDF"],
    personalData: true,
    columns: [
      column("date", "Дата", 12),
      column("personnelNumber", "Табельный №", 15),
      column("employee", "Сотрудник", 28),
      column("department", "Подразделение", 24),
      column("arrival", "Приход", 20),
      column("departure", "Уход", 20),
      column("workedMinutes", "Минут", 11, true, true),
      column("flags", "Признаки", 28),
    ],
  },
  UNCONFIRMED: {
    code: "UNCONFIRMED",
    title: "Неподтвержденные операции",
    description: "Единая очередь решений, незакрытых смен и расхождений.",
    formats: ["XLSX", "PDF"],
    personalData: false,
    columns: [
      column("date", "Дата", 12),
      column("module", "Раздел", 20),
      column("kind", "Операция", 26),
      column("reference", "Объект", 30),
      column("status", "Статус", 20),
      column("ageHours", "Возраст, ч", 12, true),
      column("href", "Ссылка", 28),
    ],
  },
};

export const REPORT_CATALOG = Object.values(REPORT_DEFINITIONS).map(
  ({ columns: _columns, ...item }) => item,
);
